// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssrpawzetqzavptuivzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcnBhd3pldHF6YXZwdHVpdnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzM1OTMsImV4cCI6MjA2MzQwOTU5M30.fJCaQ7eGI_mqirA5y1983fdTTsFT4XEj1-sSToJK8DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);